[package]
name = "unlock_ceph"
version = "1.0.0"
authors = ["Chris MacNaughton <chmacnaughton@gmail.com>"]

[dependencies]
clap = "2.1"
hashicorp_vault = "0.3"
log = "0.3"
rust-crypto = "^0.2"
simple_logger = "0.4"
walkdir = "0.1"

[dev-dependencies]
rand = "0.3"
